apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cb-coordinator
  name: cb-coordinator-svc
spec:
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: cb-coordinator
  type: NodePort
status:
  loadBalancer: {}
